apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grayscale
  template:
    metadata:
      labels:
        app: grayscale
    spec:
      containers:
        - name: grayscale
          image: leskogergo/grayscale-service:latest
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_QUEUE
              value: "grayscale"
            - name: NEXT_QUEUE
              value: "objectdetect"
