apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"imagegrab-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"imagegrab"}}}
  creationTimestamp: "2025-05-21T06:20:47Z"
  name: imagegrab-service
  namespace: default
  resourceVersion: "845"
  uid: c3104da9-3258-42b3-a37c-a3c909380c2c
spec:
  clusterIP: 10.43.47.165
  clusterIPs:
  - 10.43.47.165
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: imagegrab
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
