apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagegrab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagegrab
  template:
    metadata:
      labels:
        app: imagegrab
    spec:
      containers:
        - name: imagegrab
          image: leskogergo/imagegrab:latest
          ports:
            - containerPort: 80
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: REDIS_HOST
              value: "redis-service"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: imagegrab-service
spec:
  selector:
    app: imagegrab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
