apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectdetect
  labels:
    app: objectdetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: objectdetect
  template:
    metadata:
      labels:
        app: objectdetect
    spec:
      containers:
        - name: objectdetect
          image: leskogergo/objectdetect-service:latest
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_QUEUE
              value: "objectdetect"
            - name: NEXT_QUEUE
              value: "tag"
            - name: INPUT_BUCKET
              value: "grayscale"
            - name: OUTPUT_BUCKET
              value: "objectdetect"
