apiVersion: apps/v1
kind: Deployment
metadata:
  name: resize
  labels:
    app: resize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resize
  template:
    metadata:
      labels:
        app: resize
    spec:
      containers:
        - name: resize
          image: leskogergo/resize-service:latest
          imagePullPolicy: Always
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_QUEUE
              value: "resize"
            - name: NEXT_QUEUE
              value: "grayscale"
            - name: INPUT_BUCKET
              value: "imagegrab"
            - name: OUTPUT_BUCKET
              value: "resize"
