apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag
  template:
    metadata:
      labels:
        app: tag
    spec:
      containers:
        - name: tag
          image: leskogergo/tag:latest  # ← saját image-ed
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: REDIS_HOST
              value: "redis"
            - name: INPUT_BUCKET
              value: "objectdetect-output"
            - name: ORIGINAL_BUCKET
              value: "imagegrab-raw"
            - name: OUTPUT_BUCKET
              value: "final-output"
---
apiVersion: v1
kind: Service
metadata:
  name: tag-service
spec:
  selector:
    app: tag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

