apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag
  template:
    metadata:
      labels:
        app: tag
    spec:
      containers:
        - name: tag
          image: leskogergo/tag:latest
          ports:
            - containerPort: 80
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: REDIS_HOST
              value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: tag-service
spec:
  selector:
    app: tag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
